[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.35"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/teris-io/shortid"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
