AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener using API Gateway, DynamoDB and Lambda
Resources:
  Shorten:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: shorten
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /links
            Method: post

  Redirect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: redirect
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /links/{shorten_resource}
            Method: get

  LinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: link
      AttributeDefinitions:
        - AttributeName: shorten_resource
          AttributeType: S
      KeySchema:
        - AttributeName: shorten_resource
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
